# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca26865eec54ec1bd23be716486f150fc413bd3febfd7e600e145c93209f4f9e0fee88ccc8f616fca59937caa6f8aa3306dfefce9c9f95743655d0ac42eab725

test:
  secret_key_base: f5c35358300e100093a6e108f1de2df08489e8169a36a17a34bcea1c33c450a5a9d831a9ffdad20129af9dd43665b21907534ca706a9107e9138fa4134313304

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
